COMMON_INGREDIENTS = [
    "Chicken", "Beef", "Pork", "Salmon", "Shrimp", "Tofu",
    "Rice", "Pasta", "Bread", "Flour", "Potatoes",
    "Tomatoes", "Onion", "Garlic", "Bell Pepper", "Broccoli", "Spinach",
    "Mushrooms", "Carrots", "Zucchini", "Lettuce", "Avocado", "Corn", "Peas", "Green Beans",
    "Eggs", "Milk", "Butter", "Cheese", "Cream", "Yogurt",
    "Olive Oil", "Soy Sauce", "Lemon", "Lime", "Honey",
    "Coconut Milk", "Chickpeas", "Black Beans", "Lentils",
]

STAPLE_INGREDIENTS = ["Salt", "Pepper", "Olive Oil", "Sugar", "Flour"]

RECIPES = [
    {
        "id": "1",
        "name": "Classic Margherita Pizza",
        "image": "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&h=400&fit=crop",
        "cuisine": "Italian",
        "difficulty": "Medium",
        "prepTime": 45,
        "servings": 4,
        "tags": ["vegetarian"],
        "ingredients": [
            {"name": "Flour",       "amount": 500, "unit": "g"},
            {"name": "Tomatoes",    "amount": 400, "unit": "g"},
            {"name": "Mozzarella",  "amount": 250, "unit": "g"},
            {"name": "Basil",       "amount": 10,  "unit": "leaves"},
            {"name": "Olive Oil",   "amount": 3,   "unit": "tbsp"},
            {"name": "Yeast",       "amount": 7,   "unit": "g"},
        ],
        "steps": [
            "Mehl, Hefe, Salz und Wasser mischen. 10 Minuten kneten.",
            "Den Teig 1 Stunde an einem warmen Ort gehen lassen.",
            "Tomaten mit Salz und Olivenöl zerdrücken für die Soße.",
            "Teig ausrollen und Soße gleichmäßig verteilen.",
            "Mit gerissener Mozzarella belegen und bei 250°C 12-15 Minuten backen.",
            "Frisches Basilikum und Olivenöl vor dem Servieren hinzufügen.",
        ],
    },
    {
        "id": "2",
        "name": "Chicken Stir-Fry",
        "image": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop",
        "cuisine": "Asian",
        "difficulty": "Easy",
        "prepTime": 20,
        "servings": 2,
        "tags": ["glutenFree", "lactoseFree"],
        "ingredients": [
            {"name": "Chicken",    "amount": 300, "unit": "g"},
            {"name": "Bell Pepper","amount": 2,   "unit": "pcs"},
            {"name": "Broccoli",   "amount": 200, "unit": "g"},
            {"name": "Soy Sauce",  "amount": 3,   "unit": "tbsp"},
            {"name": "Garlic",     "amount": 3,   "unit": "cloves"},
            {"name": "Rice",       "amount": 200, "unit": "g"},
        ],
        "steps": [
            "Reis nach Packungsanweisung kochen.",
            "Hähnchen in Streifen schneiden und würzen.",
            "Hähnchen in heißem Öl ca. 5 Minuten goldbraun braten.",
            "Paprika und Brokkoli dazugeben.",
            "Knoblauch und Sojasoße hinzufügen, 2 Minuten rühren.",
            "Über Reis servieren.",
        ],
    },
    {
        "id": "3",
        "name": "Creamy Mushroom Risotto",
        "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&h=400&fit=crop",
        "cuisine": "Italian",
        "difficulty": "Medium",
        "prepTime": 40,
        "servings": 4,
        "tags": ["vegetarian"],
        "ingredients": [
            {"name": "Rice",       "amount": 300, "unit": "g"},
            {"name": "Mushrooms",  "amount": 400, "unit": "g"},
            {"name": "Onion",      "amount": 1,   "unit": "pcs"},
            {"name": "Butter",     "amount": 50,  "unit": "g"},
            {"name": "Parmesan",   "amount": 80,  "unit": "g"},
            {"name": "White Wine", "amount": 150, "unit": "ml"},
            {"name": "Garlic",     "amount": 2,   "unit": "cloves"},
        ],
        "steps": [
            "Zwiebel und Knoblauch in Butter glasig dünsten.",
            "Pilze hinzufügen und goldbraun braten.",
            "Reis hinzugeben und 2 Minuten unter Rühren anrösten.",
            "Weißwein eingießen und einrühren bis er aufgesaugt ist.",
            "Warme Brühe kellenweise hinzufügen und rühren.",
            "Mit geriebenem Parmesan und Butter fertigstellen.",
        ],
    },
    {
        "id": "4",
        "name": "Fish Tacos",
        "image": "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&h=400&fit=crop",
        "cuisine": "Mexican",
        "difficulty": "Easy",
        "prepTime": 25,
        "servings": 3,
        "tags": ["lactoseFree"],
        "ingredients": [
            {"name": "Salmon",    "amount": 400, "unit": "g"},
            {"name": "Tortillas", "amount": 6,   "unit": "pcs"},
            {"name": "Avocado",   "amount": 2,   "unit": "pcs"},
            {"name": "Lime",      "amount": 2,   "unit": "pcs"},
            {"name": "Cabbage",   "amount": 200, "unit": "g"},
            {"name": "Sour Cream","amount": 100, "unit": "ml"},
        ],
        "steps": [
            "Lachs mit Chilipulver, Kreuzkümmel, Salz und Limettensaft würzen.",
            "Lachs 3-4 Minuten pro Seite in der Pfanne anbraten.",
            "Kohl hobeln und mit Limettensaft und Salz vermengen.",
            "Avocado mit Limette, Salz und Pfeffer zu Guacamole zerdrücken.",
            "Tortillas in einer trockenen Pfanne erwärmen.",
            "Tacos mit Lachs, Kohl, Guacamole und Sauerrahm belegen.",
        ],
    },
    {
        "id": "5",
        "name": "Vegetable Pad Thai",
        "image": "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&h=400&fit=crop",
        "cuisine": "Asian",
        "difficulty": "Medium",
        "prepTime": 30,
        "servings": 2,
        "tags": ["vegan", "vegetarian", "lactoseFree"],
        "ingredients": [
            {"name": "Rice Noodles", "amount": 200, "unit": "g"},
            {"name": "Tofu",         "amount": 200, "unit": "g"},
            {"name": "Bean Sprouts", "amount": 150, "unit": "g"},
            {"name": "Carrots",      "amount": 2,   "unit": "pcs"},
            {"name": "Peanuts",      "amount": 50,  "unit": "g"},
            {"name": "Soy Sauce",    "amount": 3,   "unit": "tbsp"},
            {"name": "Lime",         "amount": 1,   "unit": "pcs"},
        ],
        "steps": [
            "Reisnudeln 15 Minuten in warmem Wasser einweichen, dann abgießen.",
            "Tofu pressen, würfeln und knusprig goldbraun braten.",
            "Karotten julienieren und in heißem Öl anbraten.",
            "Nudeln, Sojasoße und Limettensaft hinzugeben.",
            "Sojasprossen und Tofu unterheben.",
            "Mit gehackten Erdnüssen und Limettenspalten servieren.",
        ],
    },
    {
        "id": "6",
        "name": "Beef Bolognese",
        "image": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop",
        "cuisine": "Italian",
        "difficulty": "Easy",
        "prepTime": 50,
        "servings": 4,
        "tags": ["lactoseFree"],
        "ingredients": [
            {"name": "Beef",      "amount": 500, "unit": "g"},
            {"name": "Pasta",     "amount": 400, "unit": "g"},
            {"name": "Tomatoes",  "amount": 400, "unit": "g"},
            {"name": "Onion",     "amount": 1,   "unit": "pcs"},
            {"name": "Carrots",   "amount": 1,   "unit": "pcs"},
            {"name": "Garlic",    "amount": 3,   "unit": "cloves"},
            {"name": "Olive Oil", "amount": 2,   "unit": "tbsp"},
        ],
        "steps": [
            "Zwiebel, Karotten und Knoblauch fein würfeln.",
            "Hackfleisch in Olivenöl anbraten und aufteilen.",
            "Gemüse hinzufügen und 5 Minuten garen.",
            "Tomaten eingießen, mit Salz und Pfeffer würzen.",
            "30 Minuten bei niedriger Hitze köcheln lassen.",
            "Pasta al dente kochen und mit der Soße servieren.",
        ],
    },
    {
        "id": "7",
        "name": "Greek Salad",
        "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&h=400&fit=crop",
        "cuisine": "Mediterranean",
        "difficulty": "Easy",
        "prepTime": 10,
        "servings": 2,
        "tags": ["vegetarian", "glutenFree"],
        "ingredients": [
            {"name": "Tomatoes",    "amount": 4,   "unit": "pcs"},
            {"name": "Cucumber",    "amount": 1,   "unit": "pcs"},
            {"name": "Feta Cheese", "amount": 200, "unit": "g"},
            {"name": "Olives",      "amount": 100, "unit": "g"},
            {"name": "Onion",       "amount": 1,   "unit": "pcs"},
            {"name": "Olive Oil",   "amount": 3,   "unit": "tbsp"},
            {"name": "Lemon",       "amount": 1,   "unit": "pcs"},
        ],
        "steps": [
            "Tomaten in Spalten und Gurke in Halbmonde schneiden.",
            "Rote Zwiebel in Ringe schneiden.",
            "Gemüse in einer großen Schüssel vermengen.",
            "Mit zerkrümeltem Feta und Oliven toppen.",
            "Olivenöl und Zitronensaft darüberträufeln.",
            "Mit Oregano, Salz und Pfeffer würzen.",
        ],
    },
    {
        "id": "8",
        "name": "Shrimp Scampi",
        "image": "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600&h=400&fit=crop",
        "cuisine": "Italian",
        "difficulty": "Easy",
        "prepTime": 20,
        "servings": 2,
        "tags": [],
        "ingredients": [
            {"name": "Shrimp",     "amount": 400, "unit": "g"},
            {"name": "Pasta",      "amount": 250, "unit": "g"},
            {"name": "Garlic",     "amount": 4,   "unit": "cloves"},
            {"name": "Butter",     "amount": 50,  "unit": "g"},
            {"name": "Lemon",      "amount": 1,   "unit": "pcs"},
            {"name": "White Wine", "amount": 100, "unit": "ml"},
        ],
        "steps": [
            "Pasta al dente kochen und 1 Tasse Kochwasser aufbewahren.",
            "Knoblauch in Butter anschwitzen bis er duftet.",
            "Garnelen 2 Minuten pro Seite garen.",
            "Mit Weißwein und Zitronensaft ablöschen.",
            "Pasta mit etwas Kochwasser unterheben.",
            "Mit Petersilie und Zitronenabrieb garnieren.",
        ],
    },
    {
        "id": "9",
        "name": "Black Bean Burritos",
        "image": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&h=400&fit=crop",
        "cuisine": "Mexican",
        "difficulty": "Easy",
        "prepTime": 20,
        "servings": 4,
        "tags": ["vegetarian"],
        "ingredients": [
            {"name": "Black Beans", "amount": 400, "unit": "g"},
            {"name": "Rice",        "amount": 200, "unit": "g"},
            {"name": "Tortillas",   "amount": 4,   "unit": "pcs"},
            {"name": "Cheese",      "amount": 150, "unit": "g"},
            {"name": "Avocado",     "amount": 1,   "unit": "pcs"},
            {"name": "Bell Pepper", "amount": 1,   "unit": "pcs"},
            {"name": "Lime",        "amount": 1,   "unit": "pcs"},
        ],
        "steps": [
            "Reis kochen und mit Limettensaft und Koriander würzen.",
            "Schwarze Bohnen mit Kreuzkümmel, Chilipulver und Knoblauch erhitzen.",
            "Paprika würfeln und weich braten.",
            "Tortillas in einer trockenen Pfanne erwärmen.",
            "Reis, Bohnen, Paprika, Käse und Avocado schichten.",
            "Fest einrollen und mit Salsa servieren.",
        ],
    },
    {
        "id": "10",
        "name": "Coconut Curry Lentils",
        "image": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop",
        "cuisine": "Indian",
        "difficulty": "Easy",
        "prepTime": 35,
        "servings": 4,
        "tags": ["vegan", "vegetarian", "glutenFree", "lactoseFree"],
        "ingredients": [
            {"name": "Lentils",       "amount": 300, "unit": "g"},
            {"name": "Coconut Milk",  "amount": 400, "unit": "ml"},
            {"name": "Tomatoes",      "amount": 400, "unit": "g"},
            {"name": "Onion",         "amount": 1,   "unit": "pcs"},
            {"name": "Garlic",        "amount": 3,   "unit": "cloves"},
            {"name": "Spinach",       "amount": 200, "unit": "g"},
            {"name": "Curry Powder",  "amount": 2,   "unit": "tbsp"},
        ],
        "steps": [
            "Zwiebel und Knoblauch weich dünsten.",
            "Currypulver 1 Minute anrösten.",
            "Linsen, Tomaten und Kokosmilch hinzufügen.",
            "25 Minuten köcheln bis Linsen weich sind.",
            "Frischen Spinat unterrühren bis er zusammenfällt.",
            "Mit Reis oder Naan-Brot servieren.",
        ],
    },
    {
        "id": "11",
        "name": "Eggs Benedict",
        "image": "https://images.unsplash.com/photo-1608039829572-9b1234ef0d3e?w=600&h=400&fit=crop",
        "cuisine": "American",
        "difficulty": "Hard",
        "prepTime": 30,
        "servings": 2,
        "tags": [],
        "ingredients": [
            {"name": "Eggs",   "amount": 4,   "unit": "pcs"},
            {"name": "Bread",  "amount": 2,   "unit": "slices"},
            {"name": "Butter", "amount": 100, "unit": "g"},
            {"name": "Lemon",  "amount": 1,   "unit": "pcs"},
            {"name": "Ham",    "amount": 4,   "unit": "slices"},
        ],
        "steps": [
            "Hollandaise: Eigelb mit Zitronensaft im Wasserbad aufschlagen.",
            "Geschmolzene Butter langsam einrühren.",
            "Eier in siedendem Wasser mit Essig pochieren.",
            "English Muffins toasten und mit Schinken belegen.",
            "Pochierte Eier obendrauf legen.",
            "Mit Hollandaise übergießen und Paprika bestreuen.",
        ],
    },
    {
        "id": "12",
        "name": "Caprese Pasta Salad",
        "image": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600&h=400&fit=crop",
        "cuisine": "Italian",
        "difficulty": "Easy",
        "prepTime": 15,
        "servings": 4,
        "tags": ["vegetarian"],
        "ingredients": [
            {"name": "Pasta",      "amount": 300, "unit": "g"},
            {"name": "Tomatoes",   "amount": 300, "unit": "g"},
            {"name": "Mozzarella", "amount": 250, "unit": "g"},
            {"name": "Basil",      "amount": 15,  "unit": "leaves"},
            {"name": "Olive Oil",  "amount": 4,   "unit": "tbsp"},
        ],
        "steps": [
            "Pasta al dente kochen, abgießen und abkühlen lassen.",
            "Tomaten halbieren und Mozzarella würfeln.",
            "Pasta, Tomaten und Mozzarella vermengen.",
            "Basilikumblätter zerreißen und hinzugeben.",
            "Olivenöl und Balsamico-Glasur darüberträufeln.",
            "Mit Salz und Pfeffer würzen und sanft mischen.",
        ],
    },
    {
        "id": "13",
        "name": "Teriyaki Salmon Bowl",
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
        "cuisine": "Asian",
        "difficulty": "Medium",
        "prepTime": 30,
        "servings": 2,
        "tags": ["lactoseFree"],
        "ingredients": [
            {"name": "Salmon",        "amount": 300, "unit": "g"},
            {"name": "Rice",          "amount": 200, "unit": "g"},
            {"name": "Soy Sauce",     "amount": 3,   "unit": "tbsp"},
            {"name": "Honey",         "amount": 2,   "unit": "tbsp"},
            {"name": "Broccoli",      "amount": 200, "unit": "g"},
            {"name": "Avocado",       "amount": 1,   "unit": "pcs"},
            {"name": "Sesame Seeds",  "amount": 1,   "unit": "tbsp"},
        ],
        "steps": [
            "Reis nach Packungsanweisung kochen.",
            "Sojasoße, Honig, Knoblauch und Ingwer für Teriyaki-Glasur mischen.",
            "Lachs mit der Haut nach unten 4 Minuten braten.",
            "Wenden und mit Teriyaki-Glasur bestreichen, 3 Minuten weiter garen.",
            "Brokkoli dämpfen bis er leuchtend grün ist.",
            "Schüsseln mit Reis, Lachs, Brokkoli, Avocado und Sesam anrichten.",
        ],
    },
    {
        "id": "14",
        "name": "Chickpea Buddha Bowl",
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop",
        "cuisine": "Mediterranean",
        "difficulty": "Easy",
        "prepTime": 25,
        "servings": 2,
        "tags": ["vegan", "vegetarian", "glutenFree", "lactoseFree"],
        "ingredients": [
            {"name": "Chickpeas", "amount": 400, "unit": "g"},
            {"name": "Spinach",   "amount": 150, "unit": "g"},
            {"name": "Avocado",   "amount": 1,   "unit": "pcs"},
            {"name": "Carrots",   "amount": 2,   "unit": "pcs"},
            {"name": "Lemon",     "amount": 1,   "unit": "pcs"},
            {"name": "Tahini",    "amount": 2,   "unit": "tbsp"},
        ],
        "steps": [
            "Kichererbsen mit Paprika und Kreuzkümmel bei 200°C 20 Min rösten.",
            "Karotten reiben und mit Zitronensaft marinieren.",
            "Dressing: Tahini, Zitrone, Knoblauch und Wasser verrühren.",
            "Spinat als Basis in Schüsseln verteilen.",
            "Mit Kichererbsen, Karotten und Avocado belegen.",
            "Mit Tahini-Dressing beträufeln.",
        ],
    },
    {
        "id": "15",
        "name": "Mushroom & Spinach Omelette",
        "image": "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&h=400&fit=crop",
        "cuisine": "French",
        "difficulty": "Easy",
        "prepTime": 15,
        "servings": 1,
        "tags": ["vegetarian", "glutenFree"],
        "ingredients": [
            {"name": "Eggs",      "amount": 3,  "unit": "pcs"},
            {"name": "Mushrooms", "amount": 100,"unit": "g"},
            {"name": "Spinach",   "amount": 50, "unit": "g"},
            {"name": "Cheese",    "amount": 30, "unit": "g"},
            {"name": "Butter",    "amount": 15, "unit": "g"},
        ],
        "steps": [
            "Eier mit Salz und Pfeffer verquirlen.",
            "Pilze in Butter goldbraun braten.",
            "Spinat hinzugeben und zusammenfallen lassen.",
            "Verquirlte Eier über das Gemüse gießen.",
            "Bei niedriger Hitze garen bis die Masse fast gestockt ist.",
            "Käse bestreuen, zusammenklappen und servieren.",
        ],
    },
    {
        "id": "16",
        "name": "Pork Ramen",
        "image": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop",
        "cuisine": "Asian",
        "difficulty": "Hard",
        "prepTime": 60,
        "servings": 2,
        "tags": ["lactoseFree"],
        "ingredients": [
            {"name": "Pork",          "amount": 300, "unit": "g"},
            {"name": "Ramen Noodles", "amount": 200, "unit": "g"},
            {"name": "Eggs",          "amount": 2,   "unit": "pcs"},
            {"name": "Soy Sauce",     "amount": 4,   "unit": "tbsp"},
            {"name": "Garlic",        "amount": 4,   "unit": "cloves"},
            {"name": "Green Onions",  "amount": 3,   "unit": "pcs"},
            {"name": "Corn",          "amount": 100, "unit": "g"},
        ],
        "steps": [
            "Schweinefleisch 45 Min in Sojasoße, Knoblauch und Ingwer schmoren.",
            "Eier 6,5 Min weich kochen, in Sojasoße marinieren.",
            "Brühe aus Schweinefleischrückständen, Sojasoße und Miso zubereiten.",
            "Ramen-Nudeln nach Packungsanweisung kochen.",
            "Geschmortes Fleisch in dünne Scheiben schneiden.",
            "Schüsseln mit Nudeln, Brühe, Fleisch, Ei, Mais und Frühlingszwiebeln anrichten.",
        ],
    },
    {
        "id": "17",
        "name": "Sweet Potato & Black Bean Chili",
        "image": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop",
        "cuisine": "American",
        "difficulty": "Easy",
        "prepTime": 40,
        "servings": 6,
        "tags": ["vegan", "vegetarian", "glutenFree", "lactoseFree"],
        "ingredients": [
            {"name": "Sweet Potatoes","amount": 2,   "unit": "pcs"},
            {"name": "Black Beans",   "amount": 400, "unit": "g"},
            {"name": "Tomatoes",      "amount": 400, "unit": "g"},
            {"name": "Onion",         "amount": 1,   "unit": "pcs"},
            {"name": "Garlic",        "amount": 3,   "unit": "cloves"},
            {"name": "Corn",          "amount": 200, "unit": "g"},
            {"name": "Bell Pepper",   "amount": 1,   "unit": "pcs"},
        ],
        "steps": [
            "Süßkartoffeln, Zwiebel und Paprika würfeln.",
            "Zwiebel und Knoblauch in Olivenöl weich dünsten.",
            "Süßkartoffelwürfel 5 Minuten mitbraten.",
            "Schwarze Bohnen, Tomaten, Mais und Gewürze hinzufügen.",
            "25 Minuten köcheln bis Süßkartoffeln weich sind.",
            "Mit Limettenspalten und Tortilla-Chips servieren.",
        ],
    },
    {
        "id": "18",
        "name": "Lemon Herb Grilled Chicken",
        "image": "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&h=400&fit=crop",
        "cuisine": "Mediterranean",
        "difficulty": "Medium",
        "prepTime": 35,
        "servings": 4,
        "tags": ["glutenFree", "lactoseFree"],
        "ingredients": [
            {"name": "Chicken",     "amount": 600, "unit": "g"},
            {"name": "Lemon",       "amount": 2,   "unit": "pcs"},
            {"name": "Garlic",      "amount": 4,   "unit": "cloves"},
            {"name": "Olive Oil",   "amount": 4,   "unit": "tbsp"},
            {"name": "Potatoes",    "amount": 500, "unit": "g"},
            {"name": "Green Beans", "amount": 200, "unit": "g"},
        ],
        "steps": [
            "Hähnchen 30 Min in Zitronensaft, Olivenöl, Knoblauch und Kräutern marinieren.",
            "Kartoffeln vierteln und mit Olivenöl und Rosmarin schwenken.",
            "Kartoffeln bei 200°C 20 Minuten backen.",
            "Hähnchen 6-7 Minuten pro Seite grillen oder braten.",
            "Grüne Bohnen 3 Minuten in Salzwasser blanchieren.",
            "Hähnchen mit Ofenkartoffeln und grünen Bohnen servieren.",
        ],
    },
    {
        "id": "19",
        "name": "Veggie Fried Rice",
        "image": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop",
        "cuisine": "Asian",
        "difficulty": "Easy",
        "prepTime": 15,
        "servings": 2,
        "tags": ["vegan", "vegetarian", "lactoseFree"],
        "ingredients": [
            {"name": "Rice",         "amount": 300, "unit": "g"},
            {"name": "Eggs",         "amount": 2,   "unit": "pcs"},
            {"name": "Carrots",      "amount": 1,   "unit": "pcs"},
            {"name": "Peas",         "amount": 100, "unit": "g"},
            {"name": "Soy Sauce",    "amount": 2,   "unit": "tbsp"},
            {"name": "Garlic",       "amount": 2,   "unit": "cloves"},
            {"name": "Green Onions", "amount": 2,   "unit": "pcs"},
        ],
        "steps": [
            "Am besten vorgekühlten Reis vom Vortag verwenden.",
            "Eier im Wok rühren, zur Seite legen.",
            "Gewürfelte Karotten und Erbsen weich braten.",
            "Reis und Sojasoße bei hoher Hitze rühren.",
            "Rührei unterheben.",
            "Mit Frühlingszwiebeln garnieren.",
        ],
    },
    {
        "id": "20",
        "name": "Pesto Pasta",
        "image": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600&h=400&fit=crop",
        "cuisine": "Italian",
        "difficulty": "Easy",
        "prepTime": 15,
        "servings": 2,
        "tags": ["vegetarian"],
        "ingredients": [
            {"name": "Pasta",     "amount": 250, "unit": "g"},
            {"name": "Basil",     "amount": 50,  "unit": "g"},
            {"name": "Parmesan",  "amount": 50,  "unit": "g"},
            {"name": "Pine Nuts", "amount": 30,  "unit": "g"},
            {"name": "Garlic",    "amount": 2,   "unit": "cloves"},
            {"name": "Olive Oil", "amount": 80,  "unit": "ml"},
        ],
        "steps": [
            "Basilikum, Pinienkerne, Knoblauch und Parmesan im Mixer pürieren.",
            "Olivenöl langsam beim Mixen einträufeln.",
            "Pasta al dente kochen, ½ Tasse Kochwasser aufbewahren.",
            "Heiße Pasta mit Pesto vermengen, Kochwasser zum Verdünnen nutzen.",
            "Mit Salz und Pfeffer abschmecken.",
            "Mit extra Parmesan und gerösteten Pinienkernen toppen.",
        ],
    },
]
